apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-secret-store-qa
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://kvtaskflow-qa.vault.azure.net"
      tenantId: "48a76a47-7c86-439b-8978-cb2fa8333c7f"
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
