apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: taskflow-qa-db-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-secret-store-qa
    kind: ClusterSecretStore
  target:
    name: taskflow-qa-db-secret
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: postgres-password
