- op: replace
  path: /data/DB_NAME
  value: "taskmanager_qa"
- op: replace
  path: /data/DATABASE_URL
  value: "jdbc:postgresql://taskflow-dev-taskflowpsqlserver.postgres.database.azure.com:5432/taskmanager_qa?sslmode=require"