apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: taskflow-prod-tls
  namespace: taskflow-prod
spec:
  secretName: taskflow-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - taskflow.catlevi.online