name: Terraform Infrastructure DEV

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infra/envs/dev/**
pr:
  branches:
    include:
      - main
  paths:
    include:
      - infra/envs/dev/**

schedules:
  - cron: "0 21 * * 5"
    displayName: Every Friday at 9:00 PM
    branches:
      include:
        - main
    always: true

variables:
  - group: terraform-variables
  - name: TF_VERSION
    value: "1.14.x"
  - name: WORKDIR
    value: infra/envs/dev

stages:
  #-----------------------------------------------------------
  # Stage 1 ; Quality and Security Checks (PR Only)
  #-----------------------------------------------------------
  - stage: QualityChecks
    displayName: 'Quality & Security Checks'
    condition: eq(variables['Build.Reaaon'], 'PullRequest')
    jobs:
      - job: Validate
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '$(TF_VERSION)'
          #---Format Check----
          - bash: terraform fmt --recursive
            workingDirectory: $(WORKDIR)

