apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: taskflow-java-podmonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  podMetricsEndpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
  namespaceSelector:
    matchNames:
      - taskflow
      - taskflow-qa
  selector:
    matchLabels:
      app: taskflow-java