apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: taskflow-java
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - taskflow
  selector:
    matchLabels:
      app: taskflow-java
  podMetricsEndpoints:
    - port: http
      path: /actuator/prometheus
      scheme: http
