apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskflow-ingress
  namespace: taskflow
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: taskflow-dev.centralindia.cloudapp.azure.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taskflow-frontend
                port:
                  number: 80
          - path: /api/java/
            pathType: Prefix
            backend:
              service:
                name: taskflow-java
                port:
                  number: 8080
          - path: /api/python/
            pathType: Prefix
            backend:
              service:
                name: taskflow-python
                port:
                  number: 8000
  tls:
      - hosts:
        - taskflow-dev.centralindia.cloudapp.azure.com
      secretName: taskflow-tls
