apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: taskflow

bases:
  - ../../base

resources:
  - namespace.yaml
  - ingress.yaml
  - clustersecretstore.yaml
  - externalsecret.yaml

images:
  - name: taskflowdevacr.azurecr.io/taskflow/frontend
    newTag: "90a8b4cf"
  - name: taskflowdevacr.azurecr.io/taskflow/backend-java
    newTag: "7fe50e73"
  - name: taskflowdevacr.azurecr.io/taskflow/backend-python
    newTag: "11aa3c2b"