apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: taskflow

bases:
  - ../../base

resources:
  - namespace.yaml
  - ingress.yaml

images:
  - name: taskflowdevacr.azurecr.io/taskflow/frontend
    newTag: latest
  - name: taskflowdevacr.azurecr.io/taskflow/backend-java
    newTag: latest
  - name: taskflowdevacr.azurecr.io/taskflow/backend-python
    newTag: sha-3ea4108b
