apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: taskflow

bases:
  - ../../base

resources:
  - namespace.yaml
  - ingress.yaml
  - clustersecretstore.yaml
  - externalsecret.yaml

images:
  - name: taskflowdevacr.azurecr.io/taskflow/frontend
    newTag: "23d5085e"
  - name: taskflowdevacr.azurecr.io/taskflow/backend-java
    newTag: "c423d289"
  - name: taskflowdevacr.azurecr.io/taskflow/backend-python
    newTag: "03cc7692"