apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-external-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/name: platform
    app.kubernetes.io/part-of: argocd
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.11.0
    helm:
      values: |
        installCRDs: true
        serviceAccount:
          annotations:
            azure.workload.identity/client-id: "95bcb5b9-557f-4d8f-bf10-a60fd39558b3" # Set via Azure portal after WI creation
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
