apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
data:
  DB_HOST: "taskflow-dev-taskflowpsqlserver.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_NAME: "taskmanager"
  DATABASE_USER: "taskmanager"
  DATABASE_URL: "postgresql://taskmanager@taskflow-dev-taskflowpsqlserver.postgres.database.azure.com:5432/taskmanager"
  JAVA_API_URL: "http://taskflow-java:8080"
  PYTHON_API_URL: "http://taskflow-python:8000"
