apiVersion: v1
kind: Service
metadata:
  name: taskflow-java
  labels:
    app: taskflow-java
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: taskflow-java
